graph TD
  subgraph Frontend
    htmlCliente[HTML Cliente]
    htmlTrabajador[HTML Trabajador]
    htmlLogin[HTML Login]
  end

  subgraph API
    PedidoController --> OrderManager
    LoginController --> Authenticator
    ViewController
  end

  subgraph Modelo
    OrderManager --> Pedido
    OrderManager --> PaymentProcessor
    Authenticator --> DataBaseManager
  end

  htmlCliente --> PedidoController
  htmlLogin --> LoginController
  htmlTrabajador --> PedidoController
